### ISSUE TITLE
Concurrent Tree::flush_async deadlocks on v0.34.6 (latest release)

### ISSUE THREAD

**Issue by ivfranco** [spacejam/sled#1308]
rustc 1.50.0 (cb75ad5db 2021-02-10)
sled v0.34.6 (latest release)
on platform x86_64-pc-windows-msvc and x86_64-apple-darwin

Concurrently calling flush_async on the same tree causes deadlock. A minimal example:

```rust
use futures::{
    stream::{self, StreamExt},
    FutureExt,
};
use std::env::temp_dir;

#[tokio::main]
async fn main() -> sled::Result<()> {
    let db = sled::open(temp_dir())?;

    let sets = (0..100).map(|i| {
        let db = db.clone();
        async move {
            db.insert(&[i], vec![0])?;
            db.flush_async().await?;
            Ok::<(), sled::Error>(())
        }
    });

    stream::iter(sets)
        .for_each_concurrent(None, |fut| fut.map(|_| ()))
        .await;
    Ok(())
}
```

dependencies:
```toml
[dependencies]
futures = "0.3.13"
sled = "0.34.6"
tokio = { version = "1.3.0", features = ["full"] }
```
However the program above won't deadlock on main, bisect shows 61803984dc1cd8c35a3d537c2a7f5538fa659fac has fixed it.
